### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by solitaryewe** [solitaryewe/solitaryewe.github.io#2]
- [ ] Colorize and use local copies of night sky graphics
- [ ] Change fonts
- [ ] Header link styling
- [ ] Sidebar link styling
- [ ] Overall link styling
- [ ] Bottom links
- [ ] Welcome for first page
- [ ] About page with thanks
- [ ] Format projects page to display in grid or similar
- [ ] Pagination formatting
- [ ] Header links on tags and categories pages
